// Code generated by MockGen. DO NOT EDIT.
// Source: golang-rest-api-template/pkg/repository (interfaces: BookPersistence,UserPersistence)
//
// Generated by this command:
//
//	mockgen -destination=mock_persistence.go -package=repository golang-rest-api-template/pkg/repository BookPersistence,UserPersistence
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	models "golang-rest-api-template/pkg/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBookPersistence is a mock of BookPersistence interface.
type MockBookPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockBookPersistenceMockRecorder
	isgomock struct{}
}

// MockBookPersistenceMockRecorder is the mock recorder for MockBookPersistence.
type MockBookPersistenceMockRecorder struct {
	mock *MockBookPersistence
}

// NewMockBookPersistence creates a new mock instance.
func NewMockBookPersistence(ctrl *gomock.Controller) *MockBookPersistence {
	mock := &MockBookPersistence{ctrl: ctrl}
	mock.recorder = &MockBookPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookPersistence) EXPECT() *MockBookPersistenceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookPersistence) Create(ctx context.Context, book *models.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, book)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBookPersistenceMockRecorder) Create(ctx, book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookPersistence)(nil).Create), ctx, book)
}

// DeleteByID mocks base method.
func (m *MockBookPersistence) DeleteByID(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockBookPersistenceMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockBookPersistence)(nil).DeleteByID), ctx, id)
}

// FirstByID mocks base method.
func (m *MockBookPersistence) FirstByID(ctx context.Context, id uint) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByID", ctx, id)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByID indicates an expected call of FirstByID.
func (mr *MockBookPersistenceMockRecorder) FirstByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByID", reflect.TypeOf((*MockBookPersistence)(nil).FirstByID), ctx, id)
}

// List mocks base method.
func (m *MockBookPersistence) List(ctx context.Context, q BookListQuery) ([]models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, q)
	ret0, _ := ret[0].([]models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBookPersistenceMockRecorder) List(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBookPersistence)(nil).List), ctx, q)
}

// PatchFields mocks base method.
func (m *MockBookPersistence) PatchFields(ctx context.Context, id uint, title, author *string) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchFields", ctx, id, title, author)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchFields indicates an expected call of PatchFields.
func (mr *MockBookPersistenceMockRecorder) PatchFields(ctx, id, title, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchFields", reflect.TypeOf((*MockBookPersistence)(nil).PatchFields), ctx, id, title, author)
}

// UpdateFields mocks base method.
func (m *MockBookPersistence) UpdateFields(ctx context.Context, id uint, title, author string) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFields", ctx, id, title, author)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFields indicates an expected call of UpdateFields.
func (mr *MockBookPersistenceMockRecorder) UpdateFields(ctx, id, title, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFields", reflect.TypeOf((*MockBookPersistence)(nil).UpdateFields), ctx, id, title, author)
}

// MockUserPersistence is a mock of UserPersistence interface.
type MockUserPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockUserPersistenceMockRecorder
	isgomock struct{}
}

// MockUserPersistenceMockRecorder is the mock recorder for MockUserPersistence.
type MockUserPersistenceMockRecorder struct {
	mock *MockUserPersistence
}

// NewMockUserPersistence creates a new mock instance.
func NewMockUserPersistence(ctrl *gomock.Controller) *MockUserPersistence {
	mock := &MockUserPersistence{ctrl: ctrl}
	mock.recorder = &MockUserPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPersistence) EXPECT() *MockUserPersistenceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserPersistence) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserPersistenceMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserPersistence)(nil).Create), ctx, user)
}

// FindByID mocks base method.
func (m *MockUserPersistence) FindByID(ctx context.Context, id uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserPersistenceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserPersistence)(nil).FindByID), ctx, id)
}

// FindByUsername mocks base method.
func (m *MockUserPersistence) FindByUsername(ctx context.Context, username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsername", ctx, username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsername indicates an expected call of FindByUsername.
func (mr *MockUserPersistenceMockRecorder) FindByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsername", reflect.TypeOf((*MockUserPersistence)(nil).FindByUsername), ctx, username)
}
