// Code generated by MockGen. DO NOT EDIT.
// Source: golang-rest-api-template/pkg/repository (interfaces: BookPersistence,UserPersistence)

// Package repository is a generated GoMock package.
package repository

import (
	models "golang-rest-api-template/pkg/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBookPersistence is a mock of BookPersistence interface.
type MockBookPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockBookPersistenceMockRecorder
}

// MockBookPersistenceMockRecorder is the mock recorder for MockBookPersistence.
type MockBookPersistenceMockRecorder struct {
	mock *MockBookPersistence
}

// NewMockBookPersistence creates a new mock instance.
func NewMockBookPersistence(ctrl *gomock.Controller) *MockBookPersistence {
	mock := &MockBookPersistence{ctrl: ctrl}
	mock.recorder = &MockBookPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookPersistence) EXPECT() *MockBookPersistenceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookPersistence) Create(arg0 *models.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBookPersistenceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookPersistence)(nil).Create), arg0)
}

// DeleteByID mocks base method.
func (m *MockBookPersistence) DeleteByID(arg0 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockBookPersistenceMockRecorder) DeleteByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockBookPersistence)(nil).DeleteByID), arg0)
}

// FirstByID mocks base method.
func (m *MockBookPersistence) FirstByID(arg0 uint) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByID", arg0)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByID indicates an expected call of FirstByID.
func (mr *MockBookPersistenceMockRecorder) FirstByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByID", reflect.TypeOf((*MockBookPersistence)(nil).FirstByID), arg0)
}

// List mocks base method.
func (m *MockBookPersistence) List(arg0, arg1 int) ([]models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBookPersistenceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBookPersistence)(nil).List), arg0, arg1)
}

// UpdateFields mocks base method.
func (m *MockBookPersistence) UpdateFields(arg0 uint, arg1, arg2 string) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFields", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFields indicates an expected call of UpdateFields.
func (mr *MockBookPersistenceMockRecorder) UpdateFields(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFields", reflect.TypeOf((*MockBookPersistence)(nil).UpdateFields), arg0, arg1, arg2)
}

// MockUserPersistence is a mock of UserPersistence interface.
type MockUserPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockUserPersistenceMockRecorder
}

// MockUserPersistenceMockRecorder is the mock recorder for MockUserPersistence.
type MockUserPersistenceMockRecorder struct {
	mock *MockUserPersistence
}

// NewMockUserPersistence creates a new mock instance.
func NewMockUserPersistence(ctrl *gomock.Controller) *MockUserPersistence {
	mock := &MockUserPersistence{ctrl: ctrl}
	mock.recorder = &MockUserPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPersistence) EXPECT() *MockUserPersistenceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserPersistence) Create(arg0 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserPersistenceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserPersistence)(nil).Create), arg0)
}

// FindByUsername mocks base method.
func (m *MockUserPersistence) FindByUsername(arg0 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsername", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsername indicates an expected call of FindByUsername.
func (mr *MockUserPersistenceMockRecorder) FindByUsername(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsername", reflect.TypeOf((*MockUserPersistence)(nil).FindByUsername), arg0)
}
