// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package dbsqlc

import (
	"context"
)

const createBook = `-- name: CreateBook :one

INSERT INTO books (owner_id, title, author)
VALUES ($1, $2, $3)
RETURNING id, owner_id, title, author, created_at, updated_at
`

type CreateBookParams struct {
	OwnerID int64
	Title   string
	Author  string
}

// Dynamic listing (filters + allowlisted sort/order + pagination) is implemented
// as hand-written parameterized pgx in book_sqlc.go; it cannot be expressed as a
// single static sqlc query. The statements below cover the type-safe CRUD paths.
func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook, arg.OwnerID, arg.Title, arg.Author)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :execrows
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBook = `-- name: GetBook :one
SELECT id, owner_id, title, author, created_at, updated_at FROM books
WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const patchBookFields = `-- name: PatchBookFields :one
UPDATE books
SET title = COALESCE($1, title),
    author = COALESCE($2, author),
    updated_at = now()
WHERE id = $3
RETURNING id, owner_id, title, author, created_at, updated_at
`

type PatchBookFieldsParams struct {
	Title  *string
	Author *string
	ID     int64
}

func (q *Queries) PatchBookFields(ctx context.Context, arg PatchBookFieldsParams) (Book, error) {
	row := q.db.QueryRow(ctx, patchBookFields, arg.Title, arg.Author, arg.ID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookFields = `-- name: UpdateBookFields :one
UPDATE books
SET title = $2,
    author = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, owner_id, title, author, created_at, updated_at
`

type UpdateBookFieldsParams struct {
	ID     int64
	Title  string
	Author string
}

func (q *Queries) UpdateBookFields(ctx context.Context, arg UpdateBookFieldsParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBookFields, arg.ID, arg.Title, arg.Author)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
