// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"time"
)

type Book struct {
	ID        int64
	OwnerID   int64
	Title     string
	Author    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	ID         int64
	UserID     int64
	TokenHash  string
	FamilyID   string
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
