// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package dbsqlc

import (
	"context"
	"time"
)

const consumeRefreshTokenIfActive = `-- name: ConsumeRefreshTokenIfActive :execrows
UPDATE refresh_tokens
SET consumed_at = $2,
    updated_at = now()
WHERE id = $1
  AND consumed_at IS NULL
  AND revoked_at IS NULL
`

type ConsumeRefreshTokenIfActiveParams struct {
	ID         int64
	ConsumedAt *time.Time
}

// ConsumeRefreshTokenIfActive marks a token consumed only when it is still active.
// The :execrows count lets the caller detect a lost race (0 rows) vs success (1 row).
func (q *Queries) ConsumeRefreshTokenIfActive(ctx context.Context, arg ConsumeRefreshTokenIfActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRefreshTokenIfActive, arg.ID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, family_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, family_id, expires_at, consumed_at, revoked_at, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	UserID    int64
	TokenHash string
	FamilyID  string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, expires_at, consumed_at, revoked_at, created_at, updated_at FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllRefreshForUser = `-- name: RevokeAllRefreshForUser :exec
UPDATE refresh_tokens
SET revoked_at = $2,
    updated_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

type RevokeAllRefreshForUserParams struct {
	UserID    int64
	RevokedAt *time.Time
}

func (q *Queries) RevokeAllRefreshForUser(ctx context.Context, arg RevokeAllRefreshForUserParams) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshForUser, arg.UserID, arg.RevokedAt)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens
SET revoked_at = $2,
    updated_at = now()
WHERE family_id = $1
  AND revoked_at IS NULL
`

type RevokeRefreshFamilyParams struct {
	FamilyID  string
	RevokedAt *time.Time
}

func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, arg.FamilyID, arg.RevokedAt)
	return err
}
